[package]
name = "sigmars-garden-solver"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.24.7", default-features = false, features = ["png"] }
itertools = "0.12.0"
mouse-rs = "0.4.2"
screenshots = "0.8.5"
